server:
  grpc:
    addr: 0.0.0.0:10000
    timeout: 60s
  grpc_web:
    addr: 0.0.0.0:10001
    timeout: 60s
database:
  driver: memory
s3:
auth:
  password_salt: test
  jwt_issuer: test
  jwt_secret: test
mq:
  driver: memory
cache:
  driver: memory
searcher:
  data:
    bleve:
      enable:
miner:
  data: