deploy_mode = "temporary"

[server.main]
host = "0.0.0.0"
port = 10000

[server.main_web]
host = "0.0.0.0"
port = 10001

[database]
driver = "memory"

[storage]
driver = "file"
host = "127.0.0.1"
port = 10002

[auth]
password_salt = "test"
token_issuer = "test"
token_secret = "test"

[mq]
driver = "memory"

[cache]
driver = "memory"

[searcher.data.bleve]
enable = ""

[miner.data]
